CREATE DATABASE authtodo;

CREATE TABLE users(
  user_id uuid DEFAULT uuid_generate_v4(),
  user_name VARCHAR(255) NOT NULL,
  user_email VARCHAR(255) NOT NULL UNIQUE,
  user_password VARCHAR(255) NOT NULL,
  PRIMARY KEY(user_id)
);

CREATE TABLE todo(
  todo_id SERIAL,
  user_id UUID ,
  description VARCHAR(255),
  PRIMARY KEY (todo_id),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);


INSERT INTO users (user_name, user_email, user_password) VALUES ('henry', 'henryly213@gmail.com', 'kthl8822');

CREATE TABLE flight_data (
  id SERIAL PRIMARY KEY,
  Drone_Number VARCHAR(50),
  Unique_Flight_No VARCHAR(50),
  Flightcount INTEGER,
  Flight_Project_or_Category VARCHAR(50),
  Flight_date DATE,
  Select_District VARCHAR(50),
  TakeoffTime time,
  Landing_Time time,
  Duration interval,
  Training_Flight BOOLEAN,
  Fresh_or_Refly VARCHAR(50),
  Area_Covered VARCHAR(50),
  Flight_height INTEGER,
  Overlap_Used VARCHAR(50),
  Temperature INTEGER,
  Windspeed INTEGER,
  Pilot_Name VARCHAR(50),
  Field_Assistant VARCHAR(50),
  Flying_Location VARCHAR(50),
  Software_Version VARCHAR(50),
  Avg_GSD INTEGER,
  Taluk VARCHAR(50),
  Villages VARCHAR(255),
  Majra VARCHAR(225),
  Gram_Panchayat VARCHAR(50),
  LGD_Code VARCHAR(50),
  Village_Count INTEGER,
  Majra_Count INTEGER,
  Base_GPS_ID VARCHAR(50),
  Fly_Log_No VARCHAR(50),
  IBase_Filename VARCHAR(50),
  Raw_Image BOOLEAN,
  Geotagged BOOLEAN,
  Battery_Number INTEGER,
  Total_Files INTEGER,
  Folder_Size VARCHAR(50),
  Remarks TEXT
);



INSERT INTO users (user_name, user_email, user_password) VALUES ('henry', 'henryly213@gmail.com', 'kthl8822');
INSERT INTO flight_data (
  drone_number,
  unique_flight_no,
  flight_count,
  flight_project_or_category,
  flight_date,
  select_district,
  takeoff_time,
  landing_time,
  duration,
  training_flight,
  fresh_or_refly,
  area_covered,
  flight_height,
  overlap_used,
  temperature,
  windspeed,
  pilot_name,
  field_assistant,
  flying_location,
  software_version,
  avg_gsd,
  taluk,
  villages,
  majra,
  gram_panchayat,
  lgd_code,
  village_count,
  majra_count,
  base_gps_id,
  fly_log_no,
  ibase_filename,
  raw_image,
  geotagged,
  battery_number,
  total_files,
  folder_size,
  remarks
) VALUES (
  '123',
  'FL123456',
  1,
  'Project A',
  '2023-05-17',
  'District X',
  '10:00 AM',
  '10:30 AM',
  '30 minutes',
  false,
  'Fresh',
  '100 acres',
  50,
  '80%',
  25,
  10,
  'John Doe',
  'Jane Smith',
  'Location A',
  '1.0.0',
  5,
  'Taluk X',
  'Village A, Village B',
  'Majra A',
  'Panchayat X',
  'LGD123',
  2,
  1,
  'GPS123',
  'LOG001',
  'file001',
  true,
  true,
  2,
  5,
  '10 MB',
  'Flight completed successfully'
);
